sudo: required
dist: trusty
language: node_js

cache:
  directories:
    - node_modules
    - ~/.selenium-assistant

node_js:
  - 'stable'

env:
  - BROWSER_PACKAGE="workbox-core"

# Read more here: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3 # give xvfb some time to start

install:
  - npm install

script:
  # Build and run the test files
  - gulp test --package="${BROWSER_PACKAGE}"
  # Build the browser bundles
  - gulp build --package="${BROWSER_PACKAGE}"

after_success:
  - npm run coveralls
  - npm run bot
