only_commits:
  files:
    - packages/sw-cli/
    - appveyor.yml
    - package.json

install:
  - ps: Install-Product node Stable
  - npm install
  - npm install -g gulp
  - cd packages/sw-cli/
  - npm install
  - cd ..

test_script:
  - node --version
  - npm --version
  - gulp test --project "sw-cli"

build: off
