name: CI

on: [pull_request]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 8
      uses: actions/setup-node@v1
      with:
        node-version: 8
    - run: npm install
    - run: npx gulp test
